name: flatpak

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: vectorchat.flatpak
          manifest-path: io.github.c0d3dump.vectorchat.yml
          cache-key: flatpak-builder-${{ github.sha }}
          verbose: true
